export default [
  // 0 Avusturya Çekya Polonya
  {
    mainTitle: "AVUSTURYA ÇEKYA POLONYA TURU",
    subTitle: "THY İLE 6 gece / 7 Gün",
    dates:
      "18 Temmuz – 01,15,29 Ağustos – 12 Eylül – 24 Ekim – 14 Kasım – 26 Aralık 2021",
    location: "Viyana (1) – Prag (2) – Krakov (2) – Varşova (1)",
    prices: [
      [
        "18 Temmuz – 01,15,29 Ağustos – 12 Eylül – 24 Ekim – 14 Kasım – 26 Aralık 2021",
        "2-3 kişilik odada kişi başı",
        "Tek kişilik oda farkı",
        "2-11,99 yaş çocuk (2 yetişkin ile aynı odada)",
        "0-1,99 yaş çocuk (2 yetişkin ile aynı odada)",
      ],
      ["4 * Oteller", "£", "£", "£", "£"],
    ],

    days: [
      {
        title: "1.Gün",
        subTitle: "İSTANBUL – VİYANA ",
        content:
          "İstanbul Havalimanı Dış Hatlar Terminali’nde saat ..:..'da buluşma. Bilet, pasaport ve bagaj işlemlerinin ardından Türk Hava Yolları’nın TK…. tarifeli seferi ile saat ..:..'de Viyana’ya hareket. Yerel saat ile saat ..:..'de Viyana’ya varış. Varışımızın ardından panoramik olarak gerçekleştireceğimiz Viyana şehir turumuza başlıyoruz. Turumuz sırasında Opera, Üniversite, Parlemento Binası, Tiyatro, Prater , Holfburg ve Müzeler bölgesi görülecek yerler arasındadır. Turumuzun ardından otelimize transfer ve serbest zaman. ",
        breakfast: "---",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: " Ekstra olarak alınacaktır.",
        currency: "Avusturya – Euro ",
      },
      {
        title: "2.Gün",
        subTitle: "VİYANA – CESKY KRUMLOV – PRAG  ",
        content:
          "Sabah kahvaltısının ardından otelden çıkış işlemlerimizi tamamlayıp Prag’a doğru hareket ediyoruz. Yol üzerinde Cesky Krumlov turumuzu gerçekleştiriyoruz. Cesky Krumlov Çek Cumhuriyeti’nin değerli bir mücevheri olmakla beraber aynı zamanda Unesco tarafından Dünya Mirasları listesinde yer alan bir kasabadır. Komünizmin en koyu dönemlerinde harap duruma gelmiş olan Cesky Kurumlov 1990’lardan itibaren tekrar yeniden doğuşunu yaşamış ve güzelliklerini ziyarete gelen tüm misafirlerine yansıtmıştır. Turumuz sonrası Prag’a doğru yola devam ediyoruz. Prag’a varışımız sonrası panoramik olarak gerçekleştireceğimiz şehir turumuzda Hradcany Kale  Bölgesi, Loretta Kilisesi, Cumhurbaşkanlığı Sarayı, yapımının 600 yıl sürdüğü neo-gotik Rönesans ve Barok özellikleri bünyesinde barınan ST.Vitüs  Katedrali, Simyacılar sokağı, Franz Kafka’nın evi, 13. yüzyılda Baş Mimar Peter Parler tarafından yaptırılan üzerinde 31 Aziz Heykelinin bulunduğu Charles Köprüsü, eski şehir meydanı, 15. yüzyılda inşa edilen üzerinde 12 Havari bulunan tarihi Astronomik saat kulesi ve TYN Kilisesi görülecek yerler arasındadır. Tur sonrası otelimize transfer ve serbest zaman.",
        breakfast: "---",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: " Ekstra olarak alınacaktır.",
        currency: "Çekya – Koruna",
      },
      {
        title: "3.Gün",
        subTitle: "PRAG – KARLOVY VARY – PRAG ",
        content:
          "Sabah erken saatte alacağımız kahvaltının ardından Kalovy Vary turumuzu gerçekleştirmek için otelimizden hareket ediyoruz. 17. ve 18. Yüzyılda Avrupa sosyetesinin ve devlet adamlarının uğrak şehri olan Karlovy Vary’nin eşsiz tabiatı içinde, yan yana inşa edilmiş onlarca muhteşem sarayı, Atatürk’ün 1918 de kaldığı oteli, Dvorak`ın, Mozart`ın, Göethe`nin, Beethoven`ın, Rus Çarı Büyük Petro’nun ve Puşkin`in evlerini gördükten sonra 12 farklı suyun çıktığı termal galerileri ziyaret edeceğiz. Turumuz sonrası yerel bir restorant’da öğle yemeğimizi alıyoruz. Yemek sonrası serbest zamanınızda kristal, porselen, granat, kehribar taşlarının ve diğer geleneksel Çek hediyelik eşyalarının satıldığı mağazalarda geçirebilirsiniz. Serbest zaman sonrası rehberinizin bilgilendireceği saatte Prag’a dönüyoruz. Akşam serbest zaman.",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: "Karlovy Vary turunda ücrete dahil olarak alınacaktır.",
        currency: "Çekya – Koruna",
      },
      {
        title: "4.Gün",
        subTitle: "PRAG - KRAKOV",
        content:
          "Sabah kahvaltısının ardından otelden çıkış işlemlerimi tamamlayıp Krakov’a doğru yola çıkıyoruz. Akşam saatlerinde varışımız sonrası Oscar ödülü almış olan Schindler’s List ve The Pianist’e ev sahipliği yapan Krakov’da yapacağımız panoramik şehir turumuzda Rynek Glowny, Belediye Kulesi, St Mary Bazilikası, Sukiennice Meydanı, Wawel Kalesi, Kumaş Borsası, Sti Florian’s Kapısı ve Florianska Caddesi, Kanonicza Caddesi görülecek yerler arasındadır. Tur sonrası otelimize transfer ve serbest zaman.",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: "Ekstra olarak alınacaktır.",
        currency: " Polonya – Zloti ",
      },
      {
        title: "5.Gün",
        subTitle: "KRAKOV – KAZIMIERZ – VIELICZKA TUZ MADENİ ",
        content:
          "Sabah kahvaltısının ardından otelimizden hareketle ilk olarak 2. Dünya savaşı öncesi Avrupa’daki Yahudilere merkezlik yapmış olan Kazimierz’i ziyaret edeceğiz. Panoramik olarak Kanlı Perşembe meydanını ve Schindler’in Fabrika müzesini göreceğiz. Ardından UNESCO Dünya Mirası Listesi’nde bulunan yeraltındaki tuz krallığı Vieliczka Tuz Madeni’ni ziyaret edeceğiz. Öğle yemeğimizi yerel bir restoranda serbest olarak aldıktan sonra rehberimizin belirleyeceği saatte hareket edip Krakov’a transferimizi gerçekleştireceğiz. Varışımız sonrası serbest zaman.",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: "Ekstra olarak alınacaktır.",
        currency: " Polonya – Zloti ",
      },
      {
        title: "6.Gün",
        subTitle: "KRAKOV – VARŞOVA",
        content:
          "Sabah kahvaltısının ardından Varşova’ya doğru yola çıkıyoruz. Keyifli bir yolculuğun ardından varışımıza istinaden panoramik olarak gerçekleştireceğimiz Varşova şehir turumuzda Kale meydanı, Barbakan Kapısı, İsimsiz Asker Anıt Mezarı, Varşova Kraliyet Sarayı, Eski şehir, Opera Binası gezeceğimiz yerler arasındadır. Şehir turumuz sonrası otelimize transfer ve serbest zaman.",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: "Ekstra olarak alınacaktır.",
        currency: " Polonya – Zloti ",
      },
      {
        title: "7.Gün",
        subTitle: "VARŞOVA – İSTANBUL",
        content:
          "Sabah kahvaltısının ardından odaların boşaltılması. Rehberimizin belirleyeceği saatte Varşova Havalimanı'na transfer. Bilet, bagaj ve pasaport işlemlerinin ardından Türk Hava Yolları’nın TK…. seferi ile saat ..:..'de İstanbul'a hareket ve saat ..:..'da İstanbul'a varış ve turumuzun sonu.",
      },
    ],
    includes: [
      "THY ile İstanbul – Viyana / Varşova – İstanbul arası ekonomi sınıfı uçuş,",
      "Havalimanı vergileri,",
      "Viyana’da 1 gece – Prag’da 2 gece – Krakov’da 2 gece ve Varşova’da 1 gece olmak üzere toplam 6 gece oda + kahvaltı konaklama",
      "Viyana, Prag ve Krakov’da yapılacak panoramik şehir turları,",
      "Havalimanı – otel – havalimanı transferleri,",
      "Tüm şehirlerarası transferler,",
      "Otel vergileri,",
      "Cesky Krumlov turu",
      "Öğle yemekli Karlovy Vary turu",
      "Kazimierz ve Vieliczka Tuz Madeni turu",
      "Türkçe rehberlik hizmetleri",
    ],
    excludes: [
      "Seyahat sağlık sigortası",
      "Yurtdışı çıkış harcı (50 TL)",
      "Programda belirtilmeyen extra turlar ve kişisel harcamalar",
      "Müze ve Ören yeri girişleri",
      "Şoför Bahşişleri",
    ],
    general_infos: [
      "Genel şartlar ‘Tur Broşürü’ nün ve ‘Tur Kayıt Sözleşmesi’nin ayrılmaz bir parçasıdır, bağımsız düşünülemez.",

      "• Tur Programımız belli bir katılım şartı ile düzenlenmektedir. Gezi için yeterli katılım sağlanamadığı takdirde, son iptal bildirim tarihi tur kalkışına 20 gün kaladır. Katılım yetersizliği nedeniyle İptal edilen tur operasyon aracılığı ile tarafınıza bildirilecektir.",
      "• Tur programında isim belirtilmeden sadece kategori bilgisi verildiği ve/veya aynı destinasyon için seçenekli bulunduğu durumlarda otel(ler) gezi hareketinden 48 saat önce acentemiz tarafından bildirilecektir.",
      "• Turlar başka acente turları ile birleştirilebilir. Bu gibi durumlarda Venn Tour misafirleri Venn Tour sorumluluğundadır.",
      "• Bu fiyat listesi ve program yeni bir fiyat listesi çıkana kadar geçerlidir.",
      "• Tüm paket programlarımızdaki fiyatlarımız minimum 10 kişiye kadar kontenjanlar ile sınırlı olup üzeri kişi sayısı gruplarınız için fiyat artışı olabilir. Lütfen fiyat bilgisi sorunuz.",
      "• Normal pasaportlarda pasaport veriliş tarihinin 10 seneden daha fazla, diğer pasaport tiplerinde ise 5 seneden daha fazla olması durumunda, seyahate katılacak kişinin geçerli vizesi olsa dahi, yurt dışına çıkamaz ve pasaporta vize alım işlemi yapılamaz. Lütfen pasaport bilgi ve detaylarınızı kontrol ediniz.",
      "• Pasaport polisi Türkiye gümrüklerinden çıkış yapılırken, Türk Vatandaşlarından veya Yabancı uyruklu vatandaşlardan, veya geçerli vizesi olan pasaportu olsa dahi, tüm pasaport tipleri için, (Umuma Mahsus, Hususi Damgalı, Hizmet Damgalı, Diplomatik) seyahat tarihi itibariyle minimum 6 ay geçerlilik şartı aramaktadır. Bu sebeple 6 aydan az geçerliliği olan pasaportlara acentemiz tarafımızdan onay verilmemektedir.6 aydan az geçerliliği olan pasaport sahiplerinin tura katılamamalarından dolayı Venn Tour’in yolcuya karşı herhangi bir tazminat yükümlülüğü yoktur.",
      "• Venn Tour geziye katılacak tüketicilerle, gemi, otel, taşıyıcı firmalar ve gezi ile ilgili diğer hizmetleri sunan her türlü üçüncü şahıs ile ve tüzel kişilikler nezdinde aracı konumundadır. Bu nedenle kendisine müracaat ile geziye kayıt olan tüketicilerin, Acente ile taşımayı üstlenen müesseseler arasında yapılmış anlaşmalar hilafına; gösterilen araç programlarında, saatlerde, yerlerinde hazır bulunmamasından, kara, hava ve deniz araçlarının her türlü gecikmelerinden, grev, terör, savaş ve savaş ihtimali bunlara veya benzer mücbir sebeplerden, ulaşım aracını kullananın kendi hatasından veya üçüncü kişilerin şahsi kusurlarından veya öngörülmez teknik hususlardan kaynaklanan her türlü aksaklıklardan, maddi, manevi hasarlı kazalardan konaklama eksik veya tesislerinin hatalı hizmetlerinden,  Acente'nin işleten sıfatı olmaması nedeni ile mevcut sorumluluğu bulunmadığını, asli fail gibi doğrudan doğruya sorumlu olmadığını taraflar bilmektedirler.",
      "• Tüm gümrüklü yurtdışı çıkışlarında kalkış günü ilgili limanda tur hareket saatinden 3 saat önce hazır bulunulması gerekmektedir. Özellikle diğer şehirlerden iç hat uçuşu ile liman yada havalimanlarına gelecek olan misafirlerin uçuş saatlerini limanda olunması gereken saate göre ayarlamaları gerekmektedir. Bu sebepten dolayı geç kalınma ve/veya durumunda tura katılamama sorumluluk yolcuya ait olup, Venn Tour’in yolcuya karşı herhangi bir tazminat yükümlülüğü yoktur. İlgili havayolunun online check in sitesi var ise, check in işlemlerini tur hareketinden 24 saat önce şahsen yapmaları tavsiye edilir. ",
      "• Venn Tour; havayolu ile yolcularımız arasında aracı konumunda olup, 28.09.1955 Lahey Protokolü’ne tabidir. Uçuş öncesinde uçak saatleri değişebilir. Tüm uçuş saatlerinin tur hareket saatinden 48 saat önce yolcu tarafından teyit edilmesi gerekmektedir. Yolcularımız uçuş detaylarının değişebileceğini bilerek ve kabul ederek turu satın almışlardır.",
      "• Tur programında dahil olan hizmetlerden otelde alınan kahvaltılar, bulunulan ülkenin kahvaltı kültürüne uygun olarak ve genelde Continental kahvaltı olarak adlandırılan tereyağı, reçel, ekmek, çay veya kahveden oluşan sınırlı bir mönü ile sunulmakta olup gruplar için gruba tahsis edilmiş ayrı bir salonda servis edilebilir.",
      "• 3 Kişilik odalar, otellerin müsaitliğine göre verilebilmekte olup, bu tip odalarda 3. Kişiye tahsis edilen yatak standart yataklardan küçüktür. 3 Kişilik odalar 1 büyük yatak + 1ilave yataktan oluşmaktadır. İlave yataklar açma-kapama ve coach bed olarak adlandırılan yataklardan oluştukları için tur katılımcısı 3. Kişi ve/veya çocuk rezervasyonlarında odalarda yaşanabilecek sıkışıklık ve yatak tipini kabul ettiklerini beyan etmiş sayılırlar. Çocuk indirimleri 2 yetişkin yanında kalan –yaş grubuna uyan- tek çocuk için geçerlidir.",
      "• Otellerde sınırlı sayıda TWIN (2 ayrı yataklı) oda bulunmasından dolayı, TWIN oda talebinizi rezervasyondan önce kontrol ediniz.",
      "• 18 yaş altı reşit sayılmayan çocukların anne veya babalarından biri veya her ikisi ile beraber tura katılmadığı durumlarda, tura katılım için gerekli olan muvaffakatnamelerin seyahat sırasında kişilerin yanında bulundurmaları zorunludur.",
      "• Panoramik şehir turu, şehirlerin tanıtımı için düzenlenen 2-3 saat süreli turlar olup içeriği değişmemek şartıyla farklı günlerde düzenlenebilir. Müze, ören yeri girişlerini içermez. Ekstra turlar, tur lideri tarafından belirlenecek kişi sayısı ile gerçekleştirilir ve günleri programın akışına göre tur lideri tarafından değiştirilebilir. Hava durumuna bağlı olarak turlar gerçekleşmeyebilir. Yerel otoriteler tarafından gezilmesine, gidilmesine herhangi bir sebeple izin verilmeyen gezi ya da turlar yapılmaz. Bu gezi ya da turların yapılamamasından Venn Tour sorumlu tutulamaz.",
      "• Kişilerin tura katılımlarında ki sağlık sorunları, hamilelik durumu, sürekli kullanımda bulundukları ilaçlar ve bu ilaçlar ile ilgili raporları yanlarında bulundurmaları gerekmektedir.",
      "• Yol üzerinde yapılacak ekstra turlarda, tura katılmayacak olan misafirlerimiz tur lideri tarafından kente girmeden önce yol üzerinde yer alan toplu ulaşım araçlarından yaralanabilecekleri dinlenme alanlarına yönlendirilecektir.",
      "• Tur – Alan – Tur Lideri - Otel bilgilendirmeleri tur hareketinden 48 saat önce operasyon departmanı tarafından mail yolu ile gönderilecektir.",
      "• Pasaport resmi bir belge niteliğinde olup herhangi bir şekilde zedelenmiş, kirlenmiş, özellikle dikişte veya sayfalarında yırtık olması gibi sebeplerden dolayı pasaport polisi sizi ülkeye sokmama yetkisine sahiptir. Böyle bir durumda sorumluluk yolcuya aittir. ",
      "• Vize başvurusu için tur bitim tarihinden itibaren en az 6 ay geçerli pasaport ve konsolosluk tarafından istenilen evraklar gerekmektedir. Bu program için Schengen Vizesi gerekmektedir.. Pasaport polisi yolcuyu ülkeye sokmama yetkisine sahiptir. Böyle bir durumda sorumluluk yolcuya aittir.",
    ],
  },

  // 1 BALTIK BAŞKENTLERİ
  {
    mainTitle: "BALTIK BAŞKENTLERİ",
    subTitle: "THY İLE 5 Gece / 6 Gün",
    dates: "11 Mayıs – 14 Haziran – 19 Temmuz – 16 Ağustos 2021",
    location: "Tallinn (2) – Riga (2) – Vilnius (1)",
    prices: [
      {
        header1: "11 Mayıs – 14 Haziran – 19 Temmuz – 16 Ağustos 2021",
        header2: "2-3 kişilik odada kişi başı",
        header3: "Tek kişilik oda farkı",
        header4: "2-11,99 yaş çocuk (2 yetişkin ile aynı odada)",
        header5: "0-1,99 yaş çocuk (2 yetişkin ile aynı odada)",
        body1: "4 * Oteller",
        body2: "£",
        body3: "£",
        body4: "£",
        body5: "£",
      },
    ],

    days: [
      {
        title: "1.Gün",
        subTitle: "İSTANBUL – TALLINN",
        content:
          "İstanbul Havalimanı Dış Hatlar Terminalinde saat ..:..'da buluşma. Bilet, bagaj ve pasaport işlemlerinin ardından Türk Hava Yolları’nın TK…. numaralı tarifeli seferiyle saat ..:..’de Tallinn’e hareket. Varışımız sonrası havalimanında bekleyen özel aracımız ile panoramik olarak gerçekleştireceğimiz Tallinn şehir turumuzu gerçekleştireceğiz. UNESCO’nun “Dünya Mirası” olarak koruma altına aldığı ve şehrin karakteristik özelliklerini taşıyan tarihi yapılar, Estonya bayrağının dalgalandığı Tall Hermann Kulesi, Toompea Kalesi, Alexander Nevsky Katedrali, Dome Kilisesi, Toompea Tepesi’nden şehrin en güzel panoramik manzarasının fotoğraflarının çekildiği St. Nicholas Kilisesi göreceğimiz yerler arasındadır. Şehir turunun bitiminde serbest zaman. Geceleme Tallinn'deki otelimizde.",
        breakfast: "---",
        lunch: "Verilecek serbest zaman da ekstra olarak alınacaktır.",
        dinner: "Verilecek serbest zaman da ekstra olarak alınacaktır.",
        currency: "Euro ",
      },
      {
        title: "2.Gün",
        subTitle: "TALLINN",
        content:
          "Sabah kahvaltısı sonrası Rocca Al Mare turumuz başlıyor. Avrupa`da sayısı az olan açık hava müzelerinden In Rocca-Al-Mare turunda 18. yy Estonya kırsal yaşamına tanık oluyoruz. Geniş bir alan üzerine kurulu açık hava müzesi, 18.yy dönemini yansıtan köy evleri, yel değirmenleri, ahşap kilisesi, köy okulu ile sizi zamanda yolculuğa çıkartarak Estonya`nın geçmişine tanık ediyor. Birbirinden farklı evlerde, eski dönem Estonyalılar’ın yaşantısı teatral olarak anlatılıyor. Turun ardından otele geri dönüş. \nRehberimizin belirleyeceği saatte misafirlerimizle akşam yemeğimizi almak üzere Viking Köyü`ne doğru yola çıkıyoruz. Viking yaşam tarzını yansıtan bu şirin restoranda ok ve balta atma, mancınık kullanma gibi aktiviteleri deneyimleyeceğiz. Bu heyecan ve eğlence dolu dakikaların ardından akşam yemeğimizi yiyoruz ve otelimize geri dönüyoruz. ",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: " Viking Köyü turunda fiyata dahil olarak alınacaktır.",
        currency: "Euro",
      },
      {
        title: "3.Gün",
        subTitle: "TALLINN – PARNU – RİGA",
        content:
          "Sabah odaların boşaltılması ve kahvaltının ardından özel otobüsümüz ile Letonya'nın başkenti Riga’ya hareket. Yol üstünde Estonya'nın yazlık kasabası olan Parnu'da mola veriyoruz. Estonya ve Letonya’nın ormanları içinde devam eden yaklaşık 5 saat süren yolculuğumuz sonrasında Riga’ya varıyoruz.  Varışımızı takiben panoramik olarak gerçekleştireceğimiz Riga şehir turumuz başlıyor. 1201 yılında kurulan Riga’daki  şehir turumuzda, Old Town denilen tarihi merkezdeki şehrin dokusuna tanık olacağımız önemli yapılar ziyaret ediliyor. St. Peter’s Kilisesi, Brotherhood of the Blackheads Evi, Dome Katedrali, Büyük ve Küçük Guildhalls, St. Jacob’s Kilisesi, Riga Kalesi, Özgürlük Heykeli ve şehrin eşsiz mimarisine tanık olacağımız yapılarıyla süslü sokakları görülecek yerler arasında yer alıyor. Şehir turunun ardından serbest zaman. Geceleme Riga'daki otelimizde.",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: "Ekstra olarak alınacaktır.",
        currency: "Euro",
      },
      {
        title: "4.Gün",
        subTitle: "RİGA",
        content:
          "Otelimizde alacağımız kahvaltının ardından Sigulda Turumuzu gerçekleştiriyoruz. Riga’ya 51 km. uzaklıktaki, Letonya’nın en güzel şehirlerinden kabul edilen Sigulda şehir turunda Sigulda Kalesi, Gauja Milli Parkı, Gutman Mağarası, Turaida Kalesi ve Müzesi panoramik olarak göreceğimiz yerler arasındadır. Kalelerin arasında gezerken kendinizi Ortaçağ Avrupası’nda hissedeceğiniz Sigulda, yemyeşil ağaçları, ovaları, Gauja Nehri’nden oluşan muhteşem doğası ile sizi büyüleyecek. Turumuzun ardından Riga’ya geri dönüyoruz. Öğleden sonra Jurmala Turumuzu gerçekleştiriyoruz. Letonya’nın Baltık Denizi kıyısında yer alan Jurmala şehir turunda bembeyaz kumsalları ve orman içerisinde yer alan romantik ağaç evleriyle Letonya’nın sayfiye bölgesi ziyaret ediliyor. Rehberimizin vereceği serbest zamanda dilerseniz yol boyunca uzanan şirin kafelerde keyif yapabilirsiniz. Turumuzun ardından otele geri dönüş. Geceleme Riga'daki otelimizde.",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: "Ekstra olarak alınacaktır.",
        currency: "Euro",
      },
      {
        title: "5.Gün",
        subTitle: "RİGA – VILNIUS",
        content:
          "Kahvaltı sonrası odaların boşaltılmasının ardından Vilnius’a hareket ediyoruz. Yolumuz üzerinde Haçlar Tepesi (Hill of Crosses) ziyaretimiz olacak. Burası Katolik Litvanya’nın kutsal yerleşim bölgesi. Bu bölgede yaklaşık 50.000 adet birbirinden farklı boylarda Hac bulunduğu tahmin ediliyor. Litvanya’nın en etkileyici yerlerinden biri olan Hill of Crosses’i gezdikten sonra, yolumuza devam ediyoruz ve Vilnius’a varıyoruz. Varışımıza istinaden panoramik Vilnius şehir turumuz başlıyor. Vilnius’ta 1200’den fazla Ortaçağ dönemine ait yapı ve 48 adet büyük kilise bulunuyor. Neris Nehri kenarında 1323 yılında Büyük Dük Gediminas tarafından kurulan Vilnius'un panoramik şehir turunda; Katedral Meydanı, Vilnius Katedrali, Gediminas Kulesi, Gediminas Heykeli, St. Peter ve St. Paul Kilisesi, St. Anne Kilisesi görüldükten sonra Subacius Tepesi’nden şehrin panoramik manzarasının fotoğrafını çekme fırsatını bulacağız. Ardından Vilnius’un önemli bir sembolü olarak kabul edilen Dawn Kapısı’nı da gezerek turumuzu tamamlayacağız. Tur sonrası verilecek serbest zamanın ardından Trakai turumuzu gerçekleştireceğiz. Vilnius’a 29 km. uzaklıktaki Trakai turunda, 15.yy’da Galve Gölü’nün ortasındaki bir yarımadaya inşa edilmiş Trakai Kalesi ve Müzesi ziyaret ediliyor. Sonrasında Vilnius'a dönüş ve serbest zaman. Geceleme Vilnius’taki otelimizde.",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: "Ekstra olarak alınacaktır.",
        currency: "Euro",
      },
      {
        title: "6.Gün",
        subTitle: "VILNIUS – ISTANBUL",
        content:
          "Kahvaltı sonrası odaların boşaltılması. Rehberimizin belirlediği saatte havalimanına hareket. Bilet, bagaj ve pasaport işlemlerinin ardından Türk Hava Yolları’nın TK…. numaralı tarifeli seferi ile saat ..:..’de İstanbul’a hareket. Yerel saate göre ..:..’de İstanbul’a varış ve turumuzun sonu.",
      },
    ],
    includes: [
      "Türk Havayolları tarifeli seferi ile İstanbul – Tallinn / Vilnius - İstanbul gidiş/dönüş ekonomi sınıfı uçak biletleri",
      "Havalimanı vergileri",
      "Otellerde 5 gece oda kahvaltı konaklama",
      "Havalimanı – Otel – Havalimanı transferleri",
      "Panoramik Tallin, Riga, Vilnius şehir turları",
      "Rocca Al Mare turu",
      "Viking Köyü turu ve akşam yemeği",
      "Sigulda turu",
      "Jurmala turu",
      "Trakai turu",
      "Türkçe rehberlik hizmeti",
    ],
    excludes: [
      "Yurt dışı çıkış harcı bedeli (50 TL)",
      "Vize ücreti",
      "Seyahat sağlık sigortası",
      "Kişisel harcamalar",
      "Programda belirtilmeyen ekstra turlar",
    ],
    general_infos: [
      "Genel şartlar  ‘Tur Broşürü’ nün  ve ‘Tur Kayıt Sözleşmesi’nin ayrılmaz bir parçasıdır, bağımsız düşünülemez.",

      "• Tur Programımız belli bir katılım şartı ile düzenlenmektedir. Gezi için yeterli katılım sağlanamadığı takdirde, son iptal bildirim tarihi tur kalkışına 20 gün kaladır. Katılım yetersizliği nedeniyle İptal edilen tur operasyon aracılığı ile tarafınıza bildirilecektir.",
      "• Tur programında isim belirtilmeden sadece kategori bilgisi verildiği ve/veya aynı destinasyon için seçenekli bulunduğu durumlarda otel(ler) gezi hareketinden 48 saat önce acentemiz tarafından bildirilecektir.",
      "• Turlar başka acente turları ile birleştirilebilir. Bu gibi durumlarda Venn Tour misafirleri Venn Tour sorumluluğundadır.",
      "• Bu fiyat listesi ve program yeni bir fiyat listesi çıkana kadar geçerlidir.",
      "• Tüm paket programlarımızdaki fiyatlarımız minimum 10 kişiye kadar kontenjanlar ile sınırlı olup üzeri kişi sayısı gruplarınız için fiyat artışı olabilir. Lütfen fiyat bilgisi sorunuz.",
      "• Normal pasaportlarda pasaport veriliş tarihinin 10 seneden daha fazla, diğer pasaport tiplerinde ise 5 seneden daha fazla olması durumunda, seyahate katılacak kişinin geçerli vizesi olsa dahi, yurt dışına çıkamaz ve pasaporta vize alım işlemi yapılamaz. Lütfen pasaport bilgi ve detaylarınızı kontrol ediniz.",
      "• Pasaport polisi Türkiye gümrüklerinden çıkış yapılırken, Türk Vatandaşlarından veya Yabancı uyruklu vatandaşlardan, veya geçerli vizesi olan pasaportu olsa dahi, tüm pasaport tipleri için, (Umuma Mahsus, Hususi Damgalı, Hizmet Damgalı, Diplomatik) seyahat tarihi itibariyle minimum 6 ay geçerlilik şartı aramaktadır. Bu sebeple 6 aydan az geçerliliği olan pasaportlara acentemiz tarafımızdan onay verilmemektedir.6 aydan az geçerliliği olan pasaport sahiplerinin tura katılamamalarından dolayı Venn Tour’in yolcuya karşı herhangi bir tazminat yükümlülüğü yoktur.",
      "• Venn Tour geziye katılacak tüketicilerle, gemi, otel, taşıyıcı firmalar ve gezi ile ilgili diğer hizmetleri sunan her türlü üçüncü şahıs ile ve tüzel kişilikler nezdinde aracı konumundadır. Bu nedenle kendisine müracaat ile geziye kayıt olan tüketicilerin, Acente ile taşımayı üstlenen müesseseler arasında yapılmış anlaşmalar hilafına; gösterilen araç programlarında, saatlerde, yerlerinde hazır bulunmamasından, kara, hava ve deniz araçlarının her türlü gecikmelerinden, grev, terör, savaş ve savaş ihtimali bunlara veya benzer mücbir sebeplerden, ulaşım aracını kullananın kendi hatasından veya üçüncü kişilerin şahsi kusurlarından veya öngörülmez teknik hususlardan kaynaklanan her türlü aksaklıklardan, maddi, manevi hasarlı kazalardan konaklama eksik veya tesislerinin hatalı hizmetlerinden,  Acente'nin işleten sıfatı olmaması nedeni ile mevcut sorumluluğu bulunmadığını, asli fail gibi doğrudan doğruya sorumlu olmadığını taraflar bilmektedirler. ",
      "• Tüm gümrüklü yurtdışı çıkışlarında kalkış günü ilgili limanda tur hareket saatinden 3 saat önce hazır bulunulması gerekmektedir. Özellikle diğer şehirlerden iç hat uçuşu ile liman yada havalimanlarına gelecek olan misafirlerin uçuş saatlerini limanda olunması gereken saate göre ayarlamaları gerekmektedir. Bu sebepten dolayı geç kalınma ve/veya durumunda tura katılamama sorumluluk yolcuya ait olup, Venn Tour’in yolcuya karşı herhangi bir tazminat yükümlülüğü yoktur. İlgili havayolunun online check in sitesi var ise, check in işlemlerini tur hareketinden 24 saat önce şahsen yapmaları tavsiye edilir. ",
      "• Venn Tour; havayolu ile yolcularımız arasında aracı konumunda olup, 28.09.1955 Lahey Protokolü’ne tabidir. Uçuş öncesinde uçak saatleri değişebilir. Tüm uçuş saatlerinin tur hareket saatinden 48 saat önce yolcu tarafından teyit edilmesi gerekmektedir. Yolcularımız uçuş detaylarının değişebileceğini bilerek ve kabul ederek turu satın almışlardır.",
      "• Tur programında dahil olan hizmetlerden otelde alınan kahvaltılar, bulunulan ülkenin kahvaltı kültürüne uygun olarak ve genelde Continental kahvaltı olarak adlandırılan tereyağı, reçel, ekmek, çay veya kahveden oluşan sınırlı bir mönü ile sunulmakta olup gruplar için gruba tahsis edilmiş ayrı bir salonda servis edilebilir.",
      "• 3 Kişilik odalar, otellerin müsaitliğine göre verilebilmekte olup, bu tip odalarda 3. Kişiye tahsis edilen yatak standart yataklardan küçüktür. 3 Kişilik odalar 1 büyük yatak + 1ilave yataktan oluşmaktadır. İlave yataklar açma-kapama ve coach bed olarak adlandırılan yataklardan oluştukları için tur katılımcısı 3. Kişi ve/veya çocuk rezervasyonlarında odalarda yaşanabilecek sıkışıklık ve yatak tipini kabul ettiklerini beyan etmiş sayılırlar. Çocuk indirimleri 2 yetişkin yanında kalan –yaş grubuna uyan- tek çocuk için geçerlidir.",
      "• Otellerde sınırlı sayıda TWIN (2 ayrı yataklı) oda bulunmasından dolayı, TWIN oda talebinizi rezervasyondan önce kontrol ediniz.",
      "• 18 yaş altı reşit sayılmayan çocukların anne veya babalarından biri veya her ikisi ile beraber tura katılmadığı durumlarda, tura katılım için gerekli olan muvaffakatnamelerin seyahat sırasında kişilerin yanında bulundurmaları zorunludur.",
      "• Panoramik şehir turu, şehirlerin tanıtımı için düzenlenen 2-3 saat süreli turlar olup içeriği değişmemek şartıyla farklı günlerde düzenlenebilir. Müze, ören yeri girişlerini içermez. Ekstra turlar, tur lideri tarafından belirlenecek kişi sayısı ile gerçekleştirilir ve günleri programın akışına göre tur lideri tarafından değiştirilebilir. Hava durumuna bağlı olarak turlar gerçekleşmeyebilir. Yerel otoriteler tarafından gezilmesine, gidilmesine herhangi bir sebeple izin verilmeyen gezi ya da turlar yapılmaz. Bu gezi ya da turların yapılamamasından Venn Tour sorumlu tutulamaz.",
      "• Kişilerin tura katılımlarında ki sağlık sorunları, hamilelik durumu, sürekli kullanımda bulundukları ilaçlar ve bu ilaçlar ile ilgili raporları yanlarında bulundurmaları gerekmektedir.",
      "• Yol üzerinde yapılacak ekstra turlarda, tura katılmayacak olan misafirlerimiz tur lideri tarafından kente girmeden önce yol üzerinde yer alan toplu ulaşım araçlarından yaralanabilecekleri dinlenme alanlarına yönlendirilecektir.",
      "• Tur – Alan – Tur Lideri - Otel bilgilendirmeleri tur hareketinden 48 saat önce operasyon departmanı tarafından mail yolu ile gönderilecektir.",
      "• Pasaport resmi bir belge niteliğinde olup herhangi bir şekilde zedelenmiş, kirlenmiş, özellikle dikişte veya sayfalarında yırtık olması gibi sebeplerden dolayı pasaport polisi sizi ülkeye sokmama yetkisine sahiptir. Böyle bir durumda sorumluluk yolcuya aittir.",
      "• Vize başvurusu için tur bitim tarihinden itibaren en az 6 ay geçerli pasaport ve konsolosluk tarafından istenilen evraklar gerekmektedir. Bu program için Schengen Vizesi gerekmektedir.. Pasaport polisi yolcuyu ülkeye sokmama yetkisine sahiptir. Böyle bir durumda sorumluluk yolcuya aittir.",
    ],
  },
  // 2
  {
    mainTitle: "GİZEMLİ FAS TURU",
    subTitle: "THY İLE VİZESİZ 7 Gece 8 Gün",
    dates: "16 Ekim – 13 Kasım – 26 Aralık 2021",
    location:
      "Kazablanka (1) – Fes (2) – Erfoud (1) – Ouarzazate (1) – Marakeş (2)",
    prices: [
      [
        "16 Ekim – 13 Kasım – 26 Aralık 2021",
        "2-3 kişilik odada kişi başı",
        "Tek kişilik oda farkı",
        "2-11,99 yaş çocuk (2 yetişkin ile aynı odada)",
        "0-1,99 yaş çocuk (2 yetişkin ile aynı odada)",
      ],
      ["4 * Oteller", "1369 USD", "230 USD", "1319 USD", "250 USD"],
    ],

    days: [
      {
        title: "1.Gün",
        subTitle: "İSTANBUL – VİYANA ",
        content:
          "İstanbul Havalimanı Dış Hatlar Terminali’nde saat ..:..'da buluşma. Bilet, pasaport ve bagaj işlemlerinin ardından Türk Hava Yolları’nın TK…. tarifeli seferi ile saat ..:..'de Viyana’ya hareket. Yerel saat ile saat ..:..'de Viyana’ya varış. Varışımızın ardından panoramik olarak gerçekleştireceğimiz Viyana şehir turumuza başlıyoruz. Turumuz sırasında Opera, Üniversite, Parlemento Binası, Tiyatro, Prater , Holfburg ve Müzeler bölgesi görülecek yerler arasındadır. Turumuzun ardından otelimize transfer ve serbest zaman. ",
        breakfast: "---",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: " Ekstra olarak alınacaktır.",
        currency: "Avusturya – Euro ",
      },
      {
        title: "2.Gün",
        subTitle: "VİYANA – CESKY KRUMLOV – PRAG  ",
        content:
          "Sabah kahvaltısının ardından otelden çıkış işlemlerimizi tamamlayıp Prag’a doğru hareket ediyoruz. Yol üzerinde Cesky Krumlov turumuzu gerçekleştiriyoruz. Cesky Krumlov Çek Cumhuriyeti’nin değerli bir mücevheri olmakla beraber aynı zamanda Unesco tarafından Dünya Mirasları listesinde yer alan bir kasabadır. Komünizmin en koyu dönemlerinde harap duruma gelmiş olan Cesky Kurumlov 1990’lardan itibaren tekrar yeniden doğuşunu yaşamış ve güzelliklerini ziyarete gelen tüm misafirlerine yansıtmıştır. Turumuz sonrası Prag’a doğru yola devam ediyoruz. Prag’a varışımız sonrası panoramik olarak gerçekleştireceğimiz şehir turumuzda Hradcany Kale  Bölgesi, Loretta Kilisesi, Cumhurbaşkanlığı Sarayı, yapımının 600 yıl sürdüğü neo-gotik Rönesans ve Barok özellikleri bünyesinde barınan ST.Vitüs  Katedrali, Simyacılar sokağı, Franz Kafka’nın evi, 13. yüzyılda Baş Mimar Peter Parler tarafından yaptırılan üzerinde 31 Aziz Heykelinin bulunduğu Charles Köprüsü, eski şehir meydanı, 15. yüzyılda inşa edilen üzerinde 12 Havari bulunan tarihi Astronomik saat kulesi ve TYN Kilisesi görülecek yerler arasındadır. Tur sonrası otelimize transfer ve serbest zaman.",
        breakfast: "---",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: " Ekstra olarak alınacaktır.",
        currency: "Çekya – Koruna",
      },
      {
        title: "3.Gün",
        subTitle: "PRAG – KARLOVY VARY – PRAG ",
        content:
          "Sabah erken saatte alacağımız kahvaltının ardından Kalovy Vary turumuzu gerçekleştirmek için otelimizden hareket ediyoruz. 17. ve 18. Yüzyılda Avrupa sosyetesinin ve devlet adamlarının uğrak şehri olan Karlovy Vary’nin eşsiz tabiatı içinde, yan yana inşa edilmiş onlarca muhteşem sarayı, Atatürk’ün 1918 de kaldığı oteli, Dvorak`ın, Mozart`ın, Göethe`nin, Beethoven`ın, Rus Çarı Büyük Petro’nun ve Puşkin`in evlerini gördükten sonra 12 farklı suyun çıktığı termal galerileri ziyaret edeceğiz. Turumuz sonrası yerel bir restorant’da öğle yemeğimizi alıyoruz. Yemek sonrası serbest zamanınızda kristal, porselen, granat, kehribar taşlarının ve diğer geleneksel Çek hediyelik eşyalarının satıldığı mağazalarda geçirebilirsiniz. Serbest zaman sonrası rehberinizin bilgilendireceği saatte Prag’a dönüyoruz. Akşam serbest zaman.",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: "Karlovy Vary turunda ücrete dahil olarak alınacaktır.",
        currency: "Çekya – Koruna",
      },
      {
        title: "4.Gün",
        subTitle: "PRAG - KRAKOV",
        content:
          "Sabah kahvaltısının ardından otelden çıkış işlemlerimi tamamlayıp Krakov’a doğru yola çıkıyoruz. Akşam saatlerinde varışımız sonrası Oscar ödülü almış olan Schindler’s List ve The Pianist’e ev sahipliği yapan Krakov’da yapacağımız panoramik şehir turumuzda Rynek Glowny, Belediye Kulesi, St Mary Bazilikası, Sukiennice Meydanı, Wawel Kalesi, Kumaş Borsası, Sti Florian’s Kapısı ve Florianska Caddesi, Kanonicza Caddesi görülecek yerler arasındadır. Tur sonrası otelimize transfer ve serbest zaman.",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: "Ekstra olarak alınacaktır.",
        currency: " Polonya – Zloti ",
      },
      {
        title: "5.Gün",
        subTitle: "KRAKOV – KAZIMIERZ – VIELICZKA TUZ MADENİ ",
        content:
          "Sabah kahvaltısının ardından otelimizden hareketle ilk olarak 2. Dünya savaşı öncesi Avrupa’daki Yahudilere merkezlik yapmış olan Kazimierz’i ziyaret edeceğiz. Panoramik olarak Kanlı Perşembe meydanını ve Schindler’in Fabrika müzesini göreceğiz. Ardından UNESCO Dünya Mirası Listesi’nde bulunan yeraltındaki tuz krallığı Vieliczka Tuz Madeni’ni ziyaret edeceğiz. Öğle yemeğimizi yerel bir restoranda serbest olarak aldıktan sonra rehberimizin belirleyeceği saatte hareket edip Krakov’a transferimizi gerçekleştireceğiz. Varışımız sonrası serbest zaman.",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: "Ekstra olarak alınacaktır.",
        currency: " Polonya – Zloti ",
      },
      {
        title: "6.Gün",
        subTitle: "KRAKOV – VARŞOVA",
        content:
          "Sabah kahvaltısının ardından Varşova’ya doğru yola çıkıyoruz. Keyifli bir yolculuğun ardından varışımıza istinaden panoramik olarak gerçekleştireceğimiz Varşova şehir turumuzda Kale meydanı, Barbakan Kapısı, İsimsiz Asker Anıt Mezarı, Varşova Kraliyet Sarayı, Eski şehir, Opera Binası gezeceğimiz yerler arasındadır. Şehir turumuz sonrası otelimize transfer ve serbest zaman.",
        breakfast: "Otelde ücrete dahil olarak alınacaktır.",
        lunch: " Ekstra olarak alınacaktır.",
        dinner: "Ekstra olarak alınacaktır.",
        currency: " Polonya – Zloti ",
      },
      {
        title: "7.Gün",
        subTitle: "VARŞOVA – İSTANBUL",
        content:
          "Sabah kahvaltısının ardından odaların boşaltılması. Rehberimizin belirleyeceği saatte Varşova Havalimanı'na transfer. Bilet, bagaj ve pasaport işlemlerinin ardından Türk Hava Yolları’nın TK…. seferi ile saat ..:..'de İstanbul'a hareket ve saat ..:..'da İstanbul'a varış ve turumuzun sonu.",
      },
    ],
    includes: [
      "THY ile İstanbul – Viyana / Varşova – İstanbul arası ekonomi sınıfı uçuş,",
      "Havalimanı vergileri,",
      "Viyana’da 1 gece – Prag’da 2 gece – Krakov’da 2 gece ve Varşova’da 1 gece olmak üzere toplam 6 gece oda + kahvaltı konaklama",
      "Viyana, Prag ve Krakov’da yapılacak panoramik şehir turları,",
      "Havalimanı – otel – havalimanı transferleri,",
      "Tüm şehirlerarası transferler,",
      "Otel vergileri,",
      "Cesky Krumlov turu",
      "Öğle yemekli Karlovy Vary turu",
      "Kazimierz ve Vieliczka Tuz Madeni turu",
      "Türkçe rehberlik hizmetleri",
    ],
    excludes: [
      "Seyahat sağlık sigortası",
      "Yurtdışı çıkış harcı (50 TL)",
      "Programda belirtilmeyen extra turlar ve kişisel harcamalar",
      "Müze ve Ören yeri girişleri",
      "Şoför Bahşişleri",
    ],
    general_infos: [
      "Genel şartlar ‘Tur Broşürü’ nün ve ‘Tur Kayıt Sözleşmesi’nin ayrılmaz bir parçasıdır, bağımsız düşünülemez.",

      "• Tur Programımız belli bir katılım şartı ile düzenlenmektedir. Gezi için yeterli katılım sağlanamadığı takdirde, son iptal bildirim tarihi tur kalkışına 20 gün kaladır. Katılım yetersizliği nedeniyle İptal edilen tur operasyon aracılığı ile tarafınıza bildirilecektir.",
      "• Tur programında isim belirtilmeden sadece kategori bilgisi verildiği ve/veya aynı destinasyon için seçenekli bulunduğu durumlarda otel(ler) gezi hareketinden 48 saat önce acentemiz tarafından bildirilecektir.",
      "• Turlar başka acente turları ile birleştirilebilir. Bu gibi durumlarda Venn Tour misafirleri Venn Tour sorumluluğundadır.",
      "• Bu fiyat listesi ve program yeni bir fiyat listesi çıkana kadar geçerlidir.",
      "• Tüm paket programlarımızdaki fiyatlarımız minimum 10 kişiye kadar kontenjanlar ile sınırlı olup üzeri kişi sayısı gruplarınız için fiyat artışı olabilir. Lütfen fiyat bilgisi sorunuz.",
      "• Normal pasaportlarda pasaport veriliş tarihinin 10 seneden daha fazla, diğer pasaport tiplerinde ise 5 seneden daha fazla olması durumunda, seyahate katılacak kişinin geçerli vizesi olsa dahi, yurt dışına çıkamaz ve pasaporta vize alım işlemi yapılamaz. Lütfen pasaport bilgi ve detaylarınızı kontrol ediniz.",
      "• Pasaport polisi Türkiye gümrüklerinden çıkış yapılırken, Türk Vatandaşlarından veya Yabancı uyruklu vatandaşlardan, veya geçerli vizesi olan pasaportu olsa dahi, tüm pasaport tipleri için, (Umuma Mahsus, Hususi Damgalı, Hizmet Damgalı, Diplomatik) seyahat tarihi itibariyle minimum 6 ay geçerlilik şartı aramaktadır. Bu sebeple 6 aydan az geçerliliği olan pasaportlara acentemiz tarafımızdan onay verilmemektedir.6 aydan az geçerliliği olan pasaport sahiplerinin tura katılamamalarından dolayı Venn Tour’in yolcuya karşı herhangi bir tazminat yükümlülüğü yoktur.",
      "• Venn Tour geziye katılacak tüketicilerle, gemi, otel, taşıyıcı firmalar ve gezi ile ilgili diğer hizmetleri sunan her türlü üçüncü şahıs ile ve tüzel kişilikler nezdinde aracı konumundadır. Bu nedenle kendisine müracaat ile geziye kayıt olan tüketicilerin, Acente ile taşımayı üstlenen müesseseler arasında yapılmış anlaşmalar hilafına; gösterilen araç programlarında, saatlerde, yerlerinde hazır bulunmamasından, kara, hava ve deniz araçlarının her türlü gecikmelerinden, grev, terör, savaş ve savaş ihtimali bunlara veya benzer mücbir sebeplerden, ulaşım aracını kullananın kendi hatasından veya üçüncü kişilerin şahsi kusurlarından veya öngörülmez teknik hususlardan kaynaklanan her türlü aksaklıklardan, maddi, manevi hasarlı kazalardan konaklama eksik veya tesislerinin hatalı hizmetlerinden,  Acente'nin işleten sıfatı olmaması nedeni ile mevcut sorumluluğu bulunmadığını, asli fail gibi doğrudan doğruya sorumlu olmadığını taraflar bilmektedirler.",
      "• Tüm gümrüklü yurtdışı çıkışlarında kalkış günü ilgili limanda tur hareket saatinden 3 saat önce hazır bulunulması gerekmektedir. Özellikle diğer şehirlerden iç hat uçuşu ile liman yada havalimanlarına gelecek olan misafirlerin uçuş saatlerini limanda olunması gereken saate göre ayarlamaları gerekmektedir. Bu sebepten dolayı geç kalınma ve/veya durumunda tura katılamama sorumluluk yolcuya ait olup, Venn Tour’in yolcuya karşı herhangi bir tazminat yükümlülüğü yoktur. İlgili havayolunun online check in sitesi var ise, check in işlemlerini tur hareketinden 24 saat önce şahsen yapmaları tavsiye edilir. ",
      "• Venn Tour; havayolu ile yolcularımız arasında aracı konumunda olup, 28.09.1955 Lahey Protokolü’ne tabidir. Uçuş öncesinde uçak saatleri değişebilir. Tüm uçuş saatlerinin tur hareket saatinden 48 saat önce yolcu tarafından teyit edilmesi gerekmektedir. Yolcularımız uçuş detaylarının değişebileceğini bilerek ve kabul ederek turu satın almışlardır.",
      "• Tur programında dahil olan hizmetlerden otelde alınan kahvaltılar, bulunulan ülkenin kahvaltı kültürüne uygun olarak ve genelde Continental kahvaltı olarak adlandırılan tereyağı, reçel, ekmek, çay veya kahveden oluşan sınırlı bir mönü ile sunulmakta olup gruplar için gruba tahsis edilmiş ayrı bir salonda servis edilebilir.",
      "• 3 Kişilik odalar, otellerin müsaitliğine göre verilebilmekte olup, bu tip odalarda 3. Kişiye tahsis edilen yatak standart yataklardan küçüktür. 3 Kişilik odalar 1 büyük yatak + 1ilave yataktan oluşmaktadır. İlave yataklar açma-kapama ve coach bed olarak adlandırılan yataklardan oluştukları için tur katılımcısı 3. Kişi ve/veya çocuk rezervasyonlarında odalarda yaşanabilecek sıkışıklık ve yatak tipini kabul ettiklerini beyan etmiş sayılırlar. Çocuk indirimleri 2 yetişkin yanında kalan –yaş grubuna uyan- tek çocuk için geçerlidir.",
      "• Otellerde sınırlı sayıda TWIN (2 ayrı yataklı) oda bulunmasından dolayı, TWIN oda talebinizi rezervasyondan önce kontrol ediniz.",
      "• 18 yaş altı reşit sayılmayan çocukların anne veya babalarından biri veya her ikisi ile beraber tura katılmadığı durumlarda, tura katılım için gerekli olan muvaffakatnamelerin seyahat sırasında kişilerin yanında bulundurmaları zorunludur.",
      "• Panoramik şehir turu, şehirlerin tanıtımı için düzenlenen 2-3 saat süreli turlar olup içeriği değişmemek şartıyla farklı günlerde düzenlenebilir. Müze, ören yeri girişlerini içermez. Ekstra turlar, tur lideri tarafından belirlenecek kişi sayısı ile gerçekleştirilir ve günleri programın akışına göre tur lideri tarafından değiştirilebilir. Hava durumuna bağlı olarak turlar gerçekleşmeyebilir. Yerel otoriteler tarafından gezilmesine, gidilmesine herhangi bir sebeple izin verilmeyen gezi ya da turlar yapılmaz. Bu gezi ya da turların yapılamamasından Venn Tour sorumlu tutulamaz.",
      "• Kişilerin tura katılımlarında ki sağlık sorunları, hamilelik durumu, sürekli kullanımda bulundukları ilaçlar ve bu ilaçlar ile ilgili raporları yanlarında bulundurmaları gerekmektedir.",
      "• Yol üzerinde yapılacak ekstra turlarda, tura katılmayacak olan misafirlerimiz tur lideri tarafından kente girmeden önce yol üzerinde yer alan toplu ulaşım araçlarından yaralanabilecekleri dinlenme alanlarına yönlendirilecektir.",
      "• Tur – Alan – Tur Lideri - Otel bilgilendirmeleri tur hareketinden 48 saat önce operasyon departmanı tarafından mail yolu ile gönderilecektir.",
      "• Pasaport resmi bir belge niteliğinde olup herhangi bir şekilde zedelenmiş, kirlenmiş, özellikle dikişte veya sayfalarında yırtık olması gibi sebeplerden dolayı pasaport polisi sizi ülkeye sokmama yetkisine sahiptir. Böyle bir durumda sorumluluk yolcuya aittir. ",
      "• Vize başvurusu için tur bitim tarihinden itibaren en az 6 ay geçerli pasaport ve konsolosluk tarafından istenilen evraklar gerekmektedir. Bu program için Schengen Vizesi gerekmektedir.. Pasaport polisi yolcuyu ülkeye sokmama yetkisine sahiptir. Böyle bir durumda sorumluluk yolcuya aittir.",
    ],
  },
];
